# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Choi Jaewon
title: Backend Engineer
email: chjw0265@gmail.com
website: www.jjjaewon.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  choijaewon323
instagram_username: cccjjwww

about_profile_image: #
about_content: | 
  글 읽기를 좋아하는 백엔드 개발자 최재원입니다. 

content:
  - title: Skills
    layout: text
    content: |
      - Back-End : Spring Boot, Spring Data JPA
      - Front-End : HTML, CSS, JavaScript, JQuery, Thymeleaf, Bootstrap
      - Database : MariaDB, H2Database

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 블로그 프로젝트
        link: github.com/choijaewon323/BlogProject
        # link_text: Project Website
        additional_links:
          - title:  BlogProject
            icon: fab fa-github
            url: github.com/choijaewon323/BlogProject
        quote: |
          2022.07.01 ~ 2022.08.01
        description: |
          Spring Boot, Thymeleaf, MariaDB, H2Database, Spring Data JPA, HTML, CSS, JavaScript, JQuery, Bootstrap
        
          스프링 부트를 이용한 블로그입니다. 로그인의 경우 세션을 이용하여 구현하였고, 검색과 댓글을 구현하였습니다. 
          
          게시글의 경우는 서버 사이드 렌더링 기술인 Thymeleaf를 사용하였고, 댓글의 경우에는 JavaScript와 JQuery를 사용하여 클라이언트 사이드 렌더링으로 구현하였습니다.

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Inha University
        caption: 2018 ~
        sub_title: Comtuper Engineering >
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
